
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package puma.central.pdp.tenant.attrservice;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-10-29T11:24:02.599+01:00
 * Generated source version: 2.5.2
 * 
 */

@javax.jws.WebService(
                      serviceName = "AttributeProviderService",
                      portName = "AttributeProviderPort",
                      targetNamespace = "http://attrservice.tenant.puma/",
                      wsdlLocation = "http://localhost:9001/attribute-service?wsdl",
                      endpointInterface = "puma.central.pdp.tenant.attrservice.AttributeProvider")
                      
public class AttributeProviderImpl implements AttributeProvider {

    private static final Logger LOG = Logger.getLogger(AttributeProviderImpl.class.getName());

    /* (non-Javadoc)
     * @see puma.central.pdp.tenant.attrservice.AttributeProvider#fetchSupportedAttributeIds(*
     */
    public java.util.List<java.lang.String> fetchSupportedAttributeIds() throws ErrorWhileProcessingException_Exception    { 
        LOG.info("Executing operation fetchSupportedAttributeIds");
        try {
            java.util.List<java.lang.String> _return = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnVal1 = "_returnVal1633550787";
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ErrorWhileProcessingException_Exception("ErrorWhileProcessingException...");
    }

    /* (non-Javadoc)
     * @see puma.central.pdp.tenant.attrservice.AttributeProvider#fetchAttribute(java.lang.String  entityId ,)java.lang.String  attributeId )*
     */
    public java.util.List<puma.central.pdp.tenant.attrservice.SimpleAttributeValue> fetchAttribute(java.lang.String entityId,java.lang.String attributeId) throws ErrorWhileProcessingException_Exception , AttributeNotFoundException_Exception    { 
        LOG.info("Executing operation fetchAttribute");
        System.out.println(entityId);
        System.out.println(attributeId);
        try {
            java.util.List<puma.central.pdp.tenant.attrservice.SimpleAttributeValue> _return = new java.util.ArrayList<puma.central.pdp.tenant.attrservice.SimpleAttributeValue>();
            puma.central.pdp.tenant.attrservice.SimpleAttributeValue _returnVal1 = new puma.central.pdp.tenant.attrservice.SimpleAttributeValue();
            _returnVal1.setType("Type-765825097");
            _returnVal1.setValue("Value-1906815194");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ErrorWhileProcessingException_Exception("ErrorWhileProcessingException...");
        //throw new AttributeNotFoundException_Exception("AttributeNotFoundException...");
    }

}
