package puma.central.pdp.tenant.attrservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-10-29T11:24:02.636+01:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://attrservice.tenant.puma/", name = "AttributeProvider")
@XmlSeeAlso({ObjectFactory.class})
public interface AttributeProvider {

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://attrservice.tenant.puma/AttributeProvider/fetchSupportedAttributeIdsRequest", output = "http://attrservice.tenant.puma/AttributeProvider/fetchSupportedAttributeIdsResponse", fault = {@FaultAction(className = ErrorWhileProcessingException_Exception.class, value = "http://attrservice.tenant.puma/AttributeProvider/fetchSupportedAttributeIds/Fault/ErrorWhileProcessingException")})
    @RequestWrapper(localName = "fetchSupportedAttributeIds", targetNamespace = "http://attrservice.tenant.puma/", className = "puma.central.pdp.tenant.attrservice.FetchSupportedAttributeIds")
    @WebMethod
    @ResponseWrapper(localName = "fetchSupportedAttributeIdsResponse", targetNamespace = "http://attrservice.tenant.puma/", className = "puma.central.pdp.tenant.attrservice.FetchSupportedAttributeIdsResponse")
    public java.util.List<java.lang.String> fetchSupportedAttributeIds() throws ErrorWhileProcessingException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://attrservice.tenant.puma/AttributeProvider/fetchAttributeRequest", output = "http://attrservice.tenant.puma/AttributeProvider/fetchAttributeResponse", fault = {@FaultAction(className = ErrorWhileProcessingException_Exception.class, value = "http://attrservice.tenant.puma/AttributeProvider/fetchAttribute/Fault/ErrorWhileProcessingException"), @FaultAction(className = AttributeNotFoundException_Exception.class, value = "http://attrservice.tenant.puma/AttributeProvider/fetchAttribute/Fault/AttributeNotFoundException")})
    @RequestWrapper(localName = "fetchAttribute", targetNamespace = "http://attrservice.tenant.puma/", className = "puma.central.pdp.tenant.attrservice.FetchAttribute")
    @WebMethod
    @ResponseWrapper(localName = "fetchAttributeResponse", targetNamespace = "http://attrservice.tenant.puma/", className = "puma.central.pdp.tenant.attrservice.FetchAttributeResponse")
    public java.util.List<puma.central.pdp.tenant.attrservice.SimpleAttributeValue> fetchAttribute(
        @WebParam(name = "entityId", targetNamespace = "")
        java.lang.String entityId,
        @WebParam(name = "attributeId", targetNamespace = "")
        java.lang.String attributeId
    ) throws ErrorWhileProcessingException_Exception, AttributeNotFoundException_Exception;
}
