
package puma.central.pdp.tenant.attrservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-10-29T11:24:02.588+01:00
 * Generated source version: 2.5.2
 */

@WebFault(name = "AttributeNotFoundException", targetNamespace = "http://attrservice.tenant.puma/")
public class AttributeNotFoundException_Exception extends Exception {
    
    private puma.central.pdp.tenant.attrservice.AttributeNotFoundException attributeNotFoundException;

    public AttributeNotFoundException_Exception() {
        super();
    }
    
    public AttributeNotFoundException_Exception(String message) {
        super(message);
    }
    
    public AttributeNotFoundException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public AttributeNotFoundException_Exception(String message, puma.central.pdp.tenant.attrservice.AttributeNotFoundException attributeNotFoundException) {
        super(message);
        this.attributeNotFoundException = attributeNotFoundException;
    }

    public AttributeNotFoundException_Exception(String message, puma.central.pdp.tenant.attrservice.AttributeNotFoundException attributeNotFoundException, Throwable cause) {
        super(message, cause);
        this.attributeNotFoundException = attributeNotFoundException;
    }

    public puma.central.pdp.tenant.attrservice.AttributeNotFoundException getFaultInfo() {
        return this.attributeNotFoundException;
    }
}
