/*******************************************************************************
 * Copyright 2014 KU Leuven Research and Developement - iMinds - Distrinet 
 * 
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 * 
 *        http://www.apache.org/licenses/LICENSE-2.0
 * 
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 *    
 *    Administrative Contact: dnet-project-office@cs.kuleuven.be
 *    Technical Contact: maarten.decat@cs.kuleuven.be
 *    Author: maarten.decat@cs.kuleuven.be
 ******************************************************************************/
package puma.central.pdp.tenant.attrservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-10-29T11:24:02.507+01:00
 * Generated source version: 2.5.2
 * 
 */
public final class AttributeProvider_AttributeProviderPort_Client {

    private static final QName SERVICE_NAME = new QName("http://attrservice.tenant.puma/", "AttributeProviderService");

    private AttributeProvider_AttributeProviderPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = AttributeProviderService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        AttributeProviderService ss = new AttributeProviderService(wsdlURL, SERVICE_NAME);
        AttributeProvider port = ss.getAttributeProviderPort();  
        
        {
        System.out.println("Invoking fetchSupportedAttributeIds...");
        try {
            java.util.List<java.lang.String> _fetchSupportedAttributeIds__return = port.fetchSupportedAttributeIds();
            System.out.println("fetchSupportedAttributeIds.result=" + _fetchSupportedAttributeIds__return);

        } catch (ErrorWhileProcessingException_Exception e) { 
            System.out.println("Expected exception: ErrorWhileProcessingException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking fetchAttribute...");
        java.lang.String _fetchAttribute_entityId = "_fetchAttribute_entityId214655900";
        java.lang.String _fetchAttribute_attributeId = "_fetchAttribute_attributeId1558808353";
        try {
            java.util.List<puma.central.pdp.tenant.attrservice.SimpleAttributeValue> _fetchAttribute__return = port.fetchAttribute(_fetchAttribute_entityId, _fetchAttribute_attributeId);
            System.out.println("fetchAttribute.result=" + _fetchAttribute__return);

        } catch (ErrorWhileProcessingException_Exception e) { 
            System.out.println("Expected exception: ErrorWhileProcessingException has occurred.");
            System.out.println(e.toString());
        } catch (AttributeNotFoundException_Exception e) { 
            System.out.println("Expected exception: AttributeNotFoundException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
