/*******************************************************************************
 * Copyright 2014 KU Leuven Research and Developement - iMinds - Distrinet 
 * 
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 * 
 *        http://www.apache.org/licenses/LICENSE-2.0
 * 
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 *    
 *    Administrative Contact: dnet-project-office@cs.kuleuven.be
 *    Technical Contact: maarten.decat@cs.kuleuven.be
 *    Author: maarten.decat@cs.kuleuven.be
 ******************************************************************************/
package puma.central.pdp.tenant.attrservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-10-29T11:24:02.576+01:00
 * Generated source version: 2.5.2
 */

@WebFault(name = "ErrorWhileProcessingException", targetNamespace = "http://attrservice.tenant.puma/")
public class ErrorWhileProcessingException_Exception extends Exception {
    
    private puma.central.pdp.tenant.attrservice.ErrorWhileProcessingException errorWhileProcessingException;

    public ErrorWhileProcessingException_Exception() {
        super();
    }
    
    public ErrorWhileProcessingException_Exception(String message) {
        super(message);
    }
    
    public ErrorWhileProcessingException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public ErrorWhileProcessingException_Exception(String message, puma.central.pdp.tenant.attrservice.ErrorWhileProcessingException errorWhileProcessingException) {
        super(message);
        this.errorWhileProcessingException = errorWhileProcessingException;
    }

    public ErrorWhileProcessingException_Exception(String message, puma.central.pdp.tenant.attrservice.ErrorWhileProcessingException errorWhileProcessingException, Throwable cause) {
        super(message, cause);
        this.errorWhileProcessingException = errorWhileProcessingException;
    }

    public puma.central.pdp.tenant.attrservice.ErrorWhileProcessingException getFaultInfo() {
        return this.errorWhileProcessingException;
    }
}
