
package puma.central.pdp.tenant.policyservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-10-29T12:20:39.400+01:00
 * Generated source version: 2.5.2
 */

@WebFault(name = "ErrorWhileProcessingException", targetNamespace = "http://policyservice.pdp.tenant.puma/")
public class ErrorWhileProcessingException_Exception extends Exception {
    
    private puma.central.pdp.tenant.policyservice.ErrorWhileProcessingException errorWhileProcessingException;

    public ErrorWhileProcessingException_Exception() {
        super();
    }
    
    public ErrorWhileProcessingException_Exception(String message) {
        super(message);
    }
    
    public ErrorWhileProcessingException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public ErrorWhileProcessingException_Exception(String message, puma.central.pdp.tenant.policyservice.ErrorWhileProcessingException errorWhileProcessingException) {
        super(message);
        this.errorWhileProcessingException = errorWhileProcessingException;
    }

    public ErrorWhileProcessingException_Exception(String message, puma.central.pdp.tenant.policyservice.ErrorWhileProcessingException errorWhileProcessingException, Throwable cause) {
        super(message, cause);
        this.errorWhileProcessingException = errorWhileProcessingException;
    }

    public puma.central.pdp.tenant.policyservice.ErrorWhileProcessingException getFaultInfo() {
        return this.errorWhileProcessingException;
    }
}
