
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package puma.central.pdp.tenant.policyservice;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-10-29T12:20:39.412+01:00
 * Generated source version: 2.5.2
 * 
 */

@javax.jws.WebService(
                      serviceName = "PolicyEvaluationServiceService",
                      portName = "PolicyEvaluationServicePort",
                      targetNamespace = "http://policyservice.pdp.tenant.puma/",
                      wsdlLocation = "http://localhost:9003/authorization-service?wsdl",
                      endpointInterface = "puma.central.pdp.tenant.policyservice.PolicyEvaluationService")
                      
public class PolicyEvaluationServiceImpl implements PolicyEvaluationService {

    private static final Logger LOG = Logger.getLogger(PolicyEvaluationServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see puma.central.pdp.tenant.policyservice.PolicyEvaluationService#getSupportedPolicyIds(*
     */
    public java.util.List<java.lang.String> getSupportedPolicyIds() { 
        LOG.info("Executing operation getSupportedPolicyIds");
        try {
            java.util.List<java.lang.String> _return = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnVal1 = "_returnVal-196261224";
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see puma.central.pdp.tenant.policyservice.PolicyEvaluationService#evaluatePolicy(java.lang.String  policyId ,)java.lang.String  xacmlRequest ,)java.util.List<puma.central.pdp.tenant.policyservice.EncodedCachedAttribute>  encodedCachedAttributes )*
     */
    public java.lang.String evaluatePolicy(java.lang.String policyId,java.lang.String xacmlRequest,java.util.List<puma.central.pdp.tenant.policyservice.EncodedCachedAttribute> encodedCachedAttributes) throws ErrorWhileProcessingException_Exception    { 
        LOG.info("Executing operation evaluatePolicy");
        System.out.println(policyId);
        System.out.println(xacmlRequest);
        System.out.println(encodedCachedAttributes);
        try {
            java.lang.String _return = "_return-1870615812";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ErrorWhileProcessingException_Exception("ErrorWhileProcessingException...");
    }

}
