package puma.central.pdp.tenant.policyservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-10-29T12:20:39.442+01:00
 * Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "PolicyEvaluationServiceService", 
                  wsdlLocation = "http://localhost:9003/authorization-service?wsdl",
                  targetNamespace = "http://policyservice.pdp.tenant.puma/") 
public class PolicyEvaluationServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://policyservice.pdp.tenant.puma/", "PolicyEvaluationServiceService");
    public final static QName PolicyEvaluationServicePort = new QName("http://policyservice.pdp.tenant.puma/", "PolicyEvaluationServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:9003/authorization-service?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PolicyEvaluationServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:9003/authorization-service?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PolicyEvaluationServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PolicyEvaluationServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PolicyEvaluationServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns PolicyEvaluationService
     */
    @WebEndpoint(name = "PolicyEvaluationServicePort")
    public PolicyEvaluationService getPolicyEvaluationServicePort() {
        return super.getPort(PolicyEvaluationServicePort, PolicyEvaluationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PolicyEvaluationService
     */
    @WebEndpoint(name = "PolicyEvaluationServicePort")
    public PolicyEvaluationService getPolicyEvaluationServicePort(WebServiceFeature... features) {
        return super.getPort(PolicyEvaluationServicePort, PolicyEvaluationService.class, features);
    }

}
